### ISSUE TITLE
офигеть

### ISSUE THREAD

**Issue by secretstation** [xastrix/l4d2-internal-base#1]
офигеть я думал это пендос какой-то а у тебя игра на русском)
где ты так кодить научился это п*зда

**Comment by mlj2** [comment]
Привет @recoil24, не знаю, я бы не сказал что это прекрасный код, и ты можешь так же кодить, но если тебе нужно что то узнать/поинтересоваться то пиши в тг - > @jsonparse

**Comment by xastrix** [comment]
Привет @recoil24, не знаю, я бы не сказал что это прекрасный код, но если тебе нужна помощь то пиши в тг - > https://t.me/jsonparse
