### ISSUE TITLE
wont compile for some reason please help Thanks 

### ISSUE THREAD

**Issue by Boof7277** [xastrix/l4d2-internal-base#2]
![image_2024-10-07_001746834](https://github.com/user-attachments/assets/b16b8f15-b074-47bd-814a-79f6a137c9e4)

**Comment by xastrix** [comment]
Hello, Compile it in Release/x86
![image](https://github.com/user-attachments/assets/c0ae3c2c-a0e5-4619-94ed-fe1c8776c6f7)

**Comment by Boof7277** [comment]
> Hello, Compile it in Release/x86 ![image](https://private-user-images.githubusercontent.com/45708305/376952543-c0ae3c2c-a0e5-4619-94ed-fe1c8776c6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDgxMzksIm5iZiI6MTcyOTEwNzgzOSwicGF0aCI6Ii80NTcwODMwNS8zNzY5NTI1NDMtYzBhZTNjMmMtYTBlNS00NjE5LTk0ZWQtZmUxYzg3NzZjNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE5NDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NTE0ZmNmNmI3NTliZDAxMmUwZDY2N2ZiYTk2MGU2MmMyZmYwYzk4Yzc5M2RlZDEzNjYwNmRiNmRlYzAxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WcfIcFd2FqqHJukgNID14r_3SdvtBX3GktI5h5FSDsA)

same issue 
![image](https://github.com/user-attachments/assets/0ac1bc55-7079-4d71-ac4b-d5e8d0b38ca7)

**Comment by xastrix** [comment]
Open l4d2/math/math.cpp and include cmath
```cpp
#include "math.h"
#include <cmath> // sin, cos - cmath

math g_math;

void math::sin_cos(float radians, float* sine, float* cosine)
{
	*sine = std::sin(radians);
	*cosine = std::cos(radians);
}

void math::angle_vectors(vec3 angles, vec3& f)
{
	float sp, sy, sr, cp, cy, cr;

	sin_cos(DEG2RAD(angles[0]), &sp, &cp);
	sin_cos(DEG2RAD(angles[1]), &sy, &cy);
	sin_cos(DEG2RAD(angles[2]), &sr, &cr);

	f[0] = cp * cy;
	f[1] = cp * sy;
	f[2] = -sp;
}
```
